### ISSUE TITLE
yas::intrusive_buffer instead of yas::shared_buffer

### ISSUE THREAD

**Issue by niXman** [SocExplorer/SpaceWireZMQ#1]
hi,

[here](https://github.com/SocExplorer/SpaceWireZMQ/blob/53ea4568ba8a6688041e070334a06d16a816ab27/src/SpaceWireZMQ.hpp#L57) and [here](https://github.com/SocExplorer/SpaceWireZMQ/blob/main/src/SpaceWireZMQ.hpp#L66) it will be better to use `yas::intrusive_buffer`, otherwise there will be additional memory allocation and copying.

**Comment by jeandet** [comment]
@niXman thank you :)
